version: '3'
services:
  proxy:
    image: nginx:alpine
    ports:
      - '80:80'
    networks:
      - frontend
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf

  web1:
    image: httpd:alpine
    volumes:
      - ./web1/html:/usr/local/apache2/htdocs
      - ./web1/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php1
      - mariadb1
    networks:
      - frontend
      - backend

  web2:
    image: httpd:alpine
    volumes:
      - ./web2/html:/usr/local/apache2/htdocs
      - ./web2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php2
      - mariadb2
    networks:
      - frontend
      - backend

  php1:
    build: './web1/php/'
    networks:
      - backend
    volumes:
      - ./web1/html:/usr/local/apache2/htdocs

  php2:
    build: './web2/php/'
    networks:
      - backend
    volumes:
      - ./web2/html:/usr/local/apache2/htdocs

  mariadb1:
    image: mariadb
    restart: always
    volumes:
      - dbdata1:/var/lib/mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword

  mariadb2:
    image: mariadb
    restart: always
    volumes:
      - dbdata2:/var/lib/mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword

volumes:
  dbdata1:
  dbdata2:

networks:
  frontend:
  backend:
